# Generated by Django 5.0.7 on 2024-07-12 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bibita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='', max_length=100)),
                ('categoria', models.IntegerField(choices=[(1, 'Bibita Piccola'), (2, 'Bibita Grande')])),
                ('disponibile', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Ingredienti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='BibitaGrande',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('administration.bibita',),
        ),
        migrations.CreateModel(
            name='BibitaPiccola',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('administration.bibita',),
        ),
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='', max_length=100)),
                ('prezzo', models.FloatField()),
                ('categoria', models.IntegerField(choices=[(1, 'Pizze Basi'), (2, 'Pizze Specialita'), (3, 'Pizze Speciali Bianche'), (4, 'Pizze Novita')], default=1)),
                ('url_immagine', models.URLField(default='')),
                ('ingredienti', models.ManyToManyField(to='administration.ingredienti')),
            ],
        ),
        migrations.CreateModel(
            name='PizzeBase',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('administration.pizza',),
        ),
        migrations.CreateModel(
            name='PizzeNovita',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('administration.pizza',),
        ),
        migrations.CreateModel(
            name='PizzeSpecialiaBianche',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('administration.pizza',),
        ),
        migrations.CreateModel(
            name='PizzeSpecialita',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('administration.pizza',),
        ),
    ]
