# Generated by Django 5.0.7 on 2024-07-12 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ingredienti',
            new_name='Ingrediente',
        ),
    ]
