# Generated by Django 5.0.7 on 2024-07-16 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0003_alter_pizza_url_immagine'),
    ]

    operations = [
        migrations.AddField(
            model_name='bibita',
            name='prezzo',
            field=models.FloatField(null=True),
        ),
    ]
