# Generated by Django 5.0.7 on 2024-07-12 20:04

import django.db.models.deletion
import phonenumber_field.modelfields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ordine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('telefono', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('data', models.DateField()),
                ('data_ordine', models.DateTimeField(auto_now_add=True)),
                ('modalita_ritiro', models.IntegerField(choices=[(1, 'Consumazione Posto'), (2, 'Ritiro'), (3, 'Consegna Domicilio')])),
                ('strada_consegna', models.CharField(default='', max_length=250)),
                ('token', models.UUIDField(default=uuid.UUID('f603ce83-b3ad-43f4-8e26-20dc581aebfb'))),
                ('status', models.IntegerField(choices=[(1, 'In Lavorazione'), (2, 'In Consegna'), (3, 'Consegnato')])),
                ('pizza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.pizza')),
            ],
        ),
    ]
