# Generated by Django 5.0.7 on 2024-07-12 20:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_alter_ordine_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordine',
            name='token',
            field=models.UUIDField(default=uuid.UUID('a725c2d0-1f67-4115-a758-6d1dfa36422c')),
        ),
    ]
