# Generated by Django 5.0.7 on 2024-07-16 13:30

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_alter_ordine_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordine',
            name='token',
            field=models.UUIDField(default=uuid.UUID('93b592ef-3216-47e7-867f-8e4a10c1a56c')),
        ),
    ]
