# Generated by Django 5.0.7 on 2024-07-16 13:56

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0005_alter_ordine_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordine',
            name='status',
            field=models.IntegerField(choices=[(1, 'In Lavorazione'), (2, 'In Consegna'), (3, 'Consegnato')], default=2),
        ),
        migrations.AlterField(
            model_name='ordine',
            name='strada_consegna',
            field=models.CharField(default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='ordine',
            name='token',
            field=models.UUIDField(default=uuid.UUID('c8cceacc-2862-4e62-ab45-c0f302a133b7')),
        ),
    ]
