# Generated by Django 5.0.7 on 2024-07-16 14:07

import django.db.models.deletion
import phonenumber_field.modelfields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0004_bibita_prezzo'),
        ('client', '0006_alter_ordine_status_alter_ordine_strada_consegna_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdineCasa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('telefono', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('data', models.DateField()),
                ('data_ordine', models.DateTimeField(auto_now_add=True)),
                ('modalita_ritiro', models.IntegerField(choices=[(1, 'Consumazione Posto'), (2, 'Ritiro'), (3, 'Consegna Domicilio')])),
                ('token', models.UUIDField(default=uuid.UUID('7a8428a2-c8ac-4c80-bd09-fc47dbb92788'))),
                ('status', models.IntegerField(choices=[(1, 'In Lavorazione'), (2, 'In Consegna'), (3, 'Consegnato')], default=2)),
                ('strada_consegna', models.CharField(default='', max_length=250, null=True)),
                ('pizza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.pizza')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrdineRitiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('telefono', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('data', models.DateField()),
                ('data_ordine', models.DateTimeField(auto_now_add=True)),
                ('modalita_ritiro', models.IntegerField(choices=[(1, 'Consumazione Posto'), (2, 'Ritiro'), (3, 'Consegna Domicilio')])),
                ('token', models.UUIDField(default=uuid.UUID('7a8428a2-c8ac-4c80-bd09-fc47dbb92788'))),
                ('status', models.IntegerField(choices=[(1, 'In Lavorazione'), (2, 'In Consegna'), (3, 'Consegnato')], default=2)),
                ('ora', models.TimeField()),
                ('pizza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.pizza')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Ordine',
        ),
    ]
