# Generated by Django 5.0.7 on 2024-07-16 14:16

import django.db.models.deletion
import phonenumber_field.modelfields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0004_bibita_prezzo'),
        ('client', '0007_ordinecasa_ordineritiro_delete_ordine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordineritiro',
            name='token',
            field=models.UUIDField(default=uuid.UUID('d8b37912-6c6e-4fc9-8f5d-2f7d74b658da')),
        ),
        migrations.CreateModel(
            name='OrdineDomicilio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('telefono', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('data', models.DateField()),
                ('data_ordine', models.DateTimeField(auto_now_add=True)),
                ('modalita_ritiro', models.IntegerField(choices=[(1, 'Consumazione Posto'), (2, 'Ritiro'), (3, 'Consegna Domicilio')])),
                ('token', models.UUIDField(default=uuid.UUID('d8b37912-6c6e-4fc9-8f5d-2f7d74b658da'))),
                ('status', models.IntegerField(choices=[(1, 'In Lavorazione'), (2, 'In Consegna'), (3, 'Consegnato')], default=2)),
                ('strada_consegna', models.CharField(default='', max_length=250, null=True)),
                ('pizza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.pizza')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='OrdineCasa',
        ),
    ]
