# Generated by Django 5.0.7 on 2024-07-16 15:08

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0010_alter_ordineconsumazioneposto_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordineconsumazioneposto',
            name='token',
            field=models.UUIDField(default=uuid.UUID('5575be41-96a7-47ae-b22e-4d08332b0563')),
        ),
        migrations.AlterField(
            model_name='ordinedomicilio',
            name='token',
            field=models.UUIDField(default=uuid.UUID('5575be41-96a7-47ae-b22e-4d08332b0563')),
        ),
        migrations.AlterField(
            model_name='ordineritiromezzogiorno',
            name='ora',
            field=models.CharField(choices=[('12-12:15', '12-12:15'), ('12:15-12:30', '12:15-12:30'), ('12:30-12:45', '12:30-12:45'), ('12:45-13', '12:45-13'), ('13-13:15', '13-13:15'), ('13:15-13:30', '13:15-13:30'), ('13:30-13:45', '13:30-13:45')], max_length=50),
        ),
        migrations.AlterField(
            model_name='ordineritiromezzogiorno',
            name='token',
            field=models.UUIDField(default=uuid.UUID('5575be41-96a7-47ae-b22e-4d08332b0563')),
        ),
        migrations.AlterField(
            model_name='ordineritirosera',
            name='ora',
            field=models.CharField(choices=[('17:45-18', '17:45-18'), ('18-18:15', '18-18:15'), ('18:15-18:30', '18:15-18:30'), ('18:30-18:45', '18:30-18:45'), ('18:45-19', '18:45-19'), ('19-19:15', '19-19:15'), ('19:15-19:30', '19:15-19:30'), ('19:30-19:45', '19:30-19:45'), ('19:45-20', '19:45-20'), ('20-20:15', '20-20:15'), ('20:15-20:30', '20:15-20:30'), ('20:30-20:45', '20:30-20:45'), ('20:45-21', '20:45-21'), ('21-21:15', '21-21:15'), ('21:15-21:30', '21:15-21:30'), ('21:30-21:45', '21:30-21:45'), ('21:45-22', '21:45-22'), ('22-22:15', '22-22:15'), ('22:15-22:30', '22:15-22:30'), ('22:30-22:45', '22:30-22:45'), ('22:45-23', '22:45-23'), ('23-23:15', '23-23:15'), ('23:15-23:30', '23:15-23:30'), ('23:30-23:45', '23:30-23:45')], max_length=50),
        ),
        migrations.AlterField(
            model_name='ordineritirosera',
            name='token',
            field=models.UUIDField(default=uuid.UUID('5575be41-96a7-47ae-b22e-4d08332b0563')),
        ),
    ]
