# Generated by Django 5.0.7 on 2024-07-18 08:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0004_bibita_prezzo'),
        ('client', '0013_alter_ordineconsumazioneposto_token_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ConsumazioneBibite',
            new_name='ConsumazioneBibita',
        ),
        migrations.AlterField(
            model_name='ordineconsumazioneposto',
            name='token',
            field=models.UUIDField(default=uuid.UUID('063fb938-da95-40c8-b8a4-2159f1069dc3')),
        ),
        migrations.AlterField(
            model_name='ordinedomicilio',
            name='token',
            field=models.UUIDField(default=uuid.UUID('063fb938-da95-40c8-b8a4-2159f1069dc3')),
        ),
        migrations.AlterField(
            model_name='ordineritiromezzogiorno',
            name='token',
            field=models.UUIDField(default=uuid.UUID('063fb938-da95-40c8-b8a4-2159f1069dc3')),
        ),
        migrations.AlterField(
            model_name='ordineritirosera',
            name='token',
            field=models.UUIDField(default=uuid.UUID('063fb938-da95-40c8-b8a4-2159f1069dc3')),
        ),
        migrations.CreateModel(
            name='ConsumazionePizza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantita', models.IntegerField(default=1)),
                ('pizza', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='administration.pizza')),
            ],
        ),
        migrations.AlterField(
            model_name='ordineconsumazioneposto',
            name='pizza',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='client.consumazionepizza'),
        ),
        migrations.AlterField(
            model_name='ordinedomicilio',
            name='pizza',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='client.consumazionepizza'),
        ),
        migrations.AlterField(
            model_name='ordineritiromezzogiorno',
            name='pizza',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='client.consumazionepizza'),
        ),
        migrations.AlterField(
            model_name='ordineritirosera',
            name='pizza',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='client.consumazionepizza'),
        ),
    ]
