# Generated by Django 5.0.7 on 2024-07-18 08:19

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0014_rename_consumazionebibite_consumazionebibita_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordineconsumazioneposto',
            name='token',
            field=models.UUIDField(default=uuid.UUID('9e3aab4a-07e4-446c-aaec-819d54ed91d0')),
        ),
        migrations.AlterField(
            model_name='ordinedomicilio',
            name='token',
            field=models.UUIDField(default=uuid.UUID('9e3aab4a-07e4-446c-aaec-819d54ed91d0')),
        ),
        migrations.AlterField(
            model_name='ordineritiromezzogiorno',
            name='token',
            field=models.UUIDField(default=uuid.UUID('9e3aab4a-07e4-446c-aaec-819d54ed91d0')),
        ),
        migrations.AlterField(
            model_name='ordineritirosera',
            name='token',
            field=models.UUIDField(default=uuid.UUID('9e3aab4a-07e4-446c-aaec-819d54ed91d0')),
        ),
    ]
