# Generated by Django 5.0.7 on 2024-07-18 08:22

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0015_alter_ordineconsumazioneposto_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordineconsumazioneposto',
            name='token',
            field=models.UUIDField(default=uuid.UUID('c335bdf6-0484-45e1-95e7-fd0e86c4cfa6')),
        ),
        migrations.AlterField(
            model_name='ordinedomicilio',
            name='token',
            field=models.UUIDField(default=uuid.UUID('c335bdf6-0484-45e1-95e7-fd0e86c4cfa6')),
        ),
        migrations.AlterField(
            model_name='ordineritiromezzogiorno',
            name='token',
            field=models.UUIDField(default=uuid.UUID('c335bdf6-0484-45e1-95e7-fd0e86c4cfa6')),
        ),
        migrations.AlterField(
            model_name='ordineritirosera',
            name='token',
            field=models.UUIDField(default=uuid.UUID('c335bdf6-0484-45e1-95e7-fd0e86c4cfa6')),
        ),
    ]
