# Generated by Django 5.0.7 on 2024-07-18 08:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0016_alter_ordineconsumazioneposto_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordineconsumazioneposto',
            name='bibita',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='client.consumazionebibita'),
        ),
        migrations.AlterField(
            model_name='ordineconsumazioneposto',
            name='token',
            field=models.UUIDField(default=uuid.UUID('28e60826-7209-4acb-9944-949cc3b09923')),
        ),
        migrations.AlterField(
            model_name='ordinedomicilio',
            name='bibita',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='client.consumazionebibita'),
        ),
        migrations.AlterField(
            model_name='ordinedomicilio',
            name='token',
            field=models.UUIDField(default=uuid.UUID('28e60826-7209-4acb-9944-949cc3b09923')),
        ),
        migrations.AlterField(
            model_name='ordineritiromezzogiorno',
            name='bibita',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='client.consumazionebibita'),
        ),
        migrations.AlterField(
            model_name='ordineritiromezzogiorno',
            name='token',
            field=models.UUIDField(default=uuid.UUID('28e60826-7209-4acb-9944-949cc3b09923')),
        ),
        migrations.AlterField(
            model_name='ordineritirosera',
            name='bibita',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='client.consumazionebibita'),
        ),
        migrations.AlterField(
            model_name='ordineritirosera',
            name='token',
            field=models.UUIDField(default=uuid.UUID('28e60826-7209-4acb-9944-949cc3b09923')),
        ),
    ]
