# Generated by Django 5.0.7 on 2024-07-18 08:48

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0017_alter_ordineconsumazioneposto_bibita_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordineconsumazioneposto',
            name='data',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='ordineconsumazioneposto',
            name='token',
            field=models.UUIDField(default=uuid.UUID('35b41e50-ef90-467b-bdf8-c869af723b5b')),
        ),
        migrations.AlterField(
            model_name='ordinedomicilio',
            name='data',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='ordinedomicilio',
            name='token',
            field=models.UUIDField(default=uuid.UUID('35b41e50-ef90-467b-bdf8-c869af723b5b')),
        ),
        migrations.AlterField(
            model_name='ordineritiromezzogiorno',
            name='data',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='ordineritiromezzogiorno',
            name='token',
            field=models.UUIDField(default=uuid.UUID('35b41e50-ef90-467b-bdf8-c869af723b5b')),
        ),
        migrations.AlterField(
            model_name='ordineritirosera',
            name='data',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='ordineritirosera',
            name='token',
            field=models.UUIDField(default=uuid.UUID('35b41e50-ef90-467b-bdf8-c869af723b5b')),
        ),
    ]
