# Generated by Django 5.0.7 on 2024-07-18 11:19

import django.db.models.deletion
import phonenumber_field.modelfields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0004_bibita_prezzo'),
        ('client', '0018_alter_ordineconsumazioneposto_data_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ordine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('telefono', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('data', models.DateField(auto_now_add=True)),
                ('data_ordine', models.DateTimeField(auto_now_add=True)),
                ('token', models.UUIDField(default=uuid.UUID('3eaa8450-e50f-4faa-a86c-844e4e7de03f'))),
            ],
        ),
        migrations.RemoveField(
            model_name='ordineconsumazioneposto',
            name='data',
        ),
        migrations.RemoveField(
            model_name='ordineconsumazioneposto',
            name='data_ordine',
        ),
        migrations.RemoveField(
            model_name='ordineconsumazioneposto',
            name='nome',
        ),
        migrations.RemoveField(
            model_name='ordineconsumazioneposto',
            name='status',
        ),
        migrations.RemoveField(
            model_name='ordineconsumazioneposto',
            name='telefono',
        ),
        migrations.RemoveField(
            model_name='ordineconsumazioneposto',
            name='token',
        ),
        migrations.RemoveField(
            model_name='ordinedomicilio',
            name='data',
        ),
        migrations.RemoveField(
            model_name='ordinedomicilio',
            name='data_ordine',
        ),
        migrations.RemoveField(
            model_name='ordinedomicilio',
            name='nome',
        ),
        migrations.RemoveField(
            model_name='ordinedomicilio',
            name='status',
        ),
        migrations.RemoveField(
            model_name='ordinedomicilio',
            name='telefono',
        ),
        migrations.RemoveField(
            model_name='ordinedomicilio',
            name='token',
        ),
        migrations.RemoveField(
            model_name='ordineritiromezzogiorno',
            name='data',
        ),
        migrations.RemoveField(
            model_name='ordineritiromezzogiorno',
            name='data_ordine',
        ),
        migrations.RemoveField(
            model_name='ordineritiromezzogiorno',
            name='nome',
        ),
        migrations.RemoveField(
            model_name='ordineritiromezzogiorno',
            name='status',
        ),
        migrations.RemoveField(
            model_name='ordineritiromezzogiorno',
            name='telefono',
        ),
        migrations.RemoveField(
            model_name='ordineritiromezzogiorno',
            name='token',
        ),
        migrations.RemoveField(
            model_name='ordineritirosera',
            name='data',
        ),
        migrations.RemoveField(
            model_name='ordineritirosera',
            name='data_ordine',
        ),
        migrations.RemoveField(
            model_name='ordineritirosera',
            name='nome',
        ),
        migrations.RemoveField(
            model_name='ordineritirosera',
            name='status',
        ),
        migrations.RemoveField(
            model_name='ordineritirosera',
            name='telefono',
        ),
        migrations.RemoveField(
            model_name='ordineritirosera',
            name='token',
        ),
        migrations.AddField(
            model_name='ordineconsumazioneposto',
            name='quanita_bibite',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ordineconsumazioneposto',
            name='quantita_pizze',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='ordinedomicilio',
            name='quanita_bibite',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ordinedomicilio',
            name='quantita_pizze',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='ordineritiromezzogiorno',
            name='quanita_bibite',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ordineritiromezzogiorno',
            name='quantita_pizze',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='ordineritirosera',
            name='quanita_bibite',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ordineritirosera',
            name='quantita_pizze',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='ordineconsumazioneposto',
            name='bibita',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='administration.bibita'),
        ),
        migrations.AlterField(
            model_name='ordineconsumazioneposto',
            name='pizza',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='administration.pizza'),
        ),
        migrations.AlterField(
            model_name='ordinedomicilio',
            name='bibita',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='administration.bibita'),
        ),
        migrations.AlterField(
            model_name='ordinedomicilio',
            name='pizza',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='administration.pizza'),
        ),
        migrations.AlterField(
            model_name='ordineritiromezzogiorno',
            name='bibita',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='administration.bibita'),
        ),
        migrations.AlterField(
            model_name='ordineritiromezzogiorno',
            name='pizza',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='administration.pizza'),
        ),
        migrations.AlterField(
            model_name='ordineritirosera',
            name='bibita',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='administration.bibita'),
        ),
        migrations.AlterField(
            model_name='ordineritirosera',
            name='pizza',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='administration.pizza'),
        ),
        migrations.AddField(
            model_name='ordineconsumazioneposto',
            name='ordine',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='client.ordine'),
        ),
        migrations.AddField(
            model_name='ordinedomicilio',
            name='ordine',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='client.ordine'),
        ),
        migrations.AddField(
            model_name='ordineritiromezzogiorno',
            name='ordine',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='client.ordine'),
        ),
        migrations.AddField(
            model_name='ordineritirosera',
            name='ordine',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='client.ordine'),
        ),
    ]
