# Generated by Django 5.0.7 on 2024-07-18 11:20

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0019_ordine_remove_ordineconsumazioneposto_data_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consumazionepizza',
            name='pizza',
        ),
        migrations.AlterField(
            model_name='ordine',
            name='token',
            field=models.UUIDField(default=uuid.UUID('583df884-a01d-4d64-83e9-8e1a03e2530e')),
        ),
        migrations.DeleteModel(
            name='ConsumazioneBibita',
        ),
        migrations.DeleteModel(
            name='ConsumazionePizza',
        ),
    ]
