# Generated by Django 5.0.7 on 2024-07-19 16:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0004_bibita_prezzo'),
        ('client', '0020_remove_consumazionepizza_pizza_alter_ordine_token_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordinedomicilio',
            name='bibita',
        ),
        migrations.RemoveField(
            model_name='ordinedomicilio',
            name='ordine',
        ),
        migrations.RemoveField(
            model_name='ordinedomicilio',
            name='pizza',
        ),
        migrations.RemoveField(
            model_name='ordineritiromezzogiorno',
            name='bibita',
        ),
        migrations.RemoveField(
            model_name='ordineritiromezzogiorno',
            name='ordine',
        ),
        migrations.RemoveField(
            model_name='ordineritiromezzogiorno',
            name='pizza',
        ),
        migrations.RemoveField(
            model_name='ordineritirosera',
            name='bibita',
        ),
        migrations.RemoveField(
            model_name='ordineritirosera',
            name='ordine',
        ),
        migrations.RemoveField(
            model_name='ordineritirosera',
            name='pizza',
        ),
        migrations.RemoveField(
            model_name='ordine',
            name='data_ordine',
        ),
        migrations.AddField(
            model_name='ordine',
            name='consegna',
            field=models.CharField(choices=[('consumazione_sul_posto', 'Consumazione sul posto'), ('ritiro', 'Ritiro'), ('consegna_al_domicilio', 'Consegna a domicilio')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ordine',
            name='nome',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='ordine',
            name='token',
            field=models.UUIDField(default=uuid.UUID('9e5af09d-3c89-47dc-b52b-74f11dec2e2f')),
        ),
        migrations.CreateModel(
            name='OggettiBibitaOrdine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantita', models.PositiveIntegerField(default=1)),
                ('bibita', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='administration.bibita')),
                ('ordine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.ordine')),
            ],
        ),
        migrations.CreateModel(
            name='OggettiPizzaOrdine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantita', models.PositiveIntegerField(default=1)),
                ('ordine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.ordine')),
                ('pizza', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='administration.pizza')),
            ],
        ),
        migrations.CreateModel(
            name='RitiroOrdineMezzogiorno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ora', models.CharField(choices=[('12-12:15', '12-12:15'), ('12:15-12:30', '12:15-12:30'), ('12:30-12:45', '12:30-12:45'), ('12:45-13', '12:45-13'), ('13-13:15', '13-13:15'), ('13:15-13:30', '13:15-13:30'), ('13:30-13:45', '13:30-13:45')], max_length=100)),
                ('ordine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.ordine')),
            ],
        ),
        migrations.CreateModel(
            name='RitiroOrdineSera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ora', models.CharField(choices=[('17:45-18', '17:45-18'), ('18-18:15', '18-18:15'), ('18:15-18:30', '18:15-18:30'), ('18:30-18:45', '18:30-18:45'), ('18:45-19', '18:45-19'), ('19-19:15', '19-19:15'), ('19:15-19:30', '19:15-19:30'), ('19:30-19:45', '19:30-19:45'), ('19:45-20', '19:45-20'), ('20-20:15', '20-20:15'), ('20:15-20:30', '20:15-20:30'), ('20:30-20:45', '20:30-20:45'), ('20:45-21', '20:45-21'), ('21-21:15', '21-21:15'), ('21:15-21:30', '21:15-21:30'), ('21:30-21:45', '21:30-21:45'), ('21:45-22', '21:45-22'), ('22-22:15', '22-22:15'), ('22:15-22:30', '22:15-22:30'), ('22:30-22:45', '22:30-22:45'), ('22:45-23', '22:45-23'), ('23-23:15', '23-23:15'), ('23:15-23:30', '23:15-23:30'), ('23:30-23:45', '23:30-23:45')], max_length=100)),
                ('ordine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.ordine')),
            ],
        ),
        migrations.CreateModel(
            name='StradaOrdine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strada', models.CharField(default='', max_length=500)),
                ('ordine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.ordine')),
            ],
        ),
        migrations.DeleteModel(
            name='OrdineConsumazionePosto',
        ),
        migrations.DeleteModel(
            name='OrdineDomicilio',
        ),
        migrations.DeleteModel(
            name='OrdineRitiroMezzogiorno',
        ),
        migrations.DeleteModel(
            name='OrdineRitiroSera',
        ),
    ]
